[buildscript_repositories]
google()

[buildscript_dependencies]
classpath 'com.google.gms:google-services:4.3.10'

[allprojects_repositories]
google()

[dependencies]
implementation platform('com.google.firebase:firebase-bom:29.3.0') 

[android_defaultconfig]

[global]
apply plugin: 'com.google.gms.google-services'

