name: "Remove Old Builds"

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  remove-old-builds:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 minute'
          skip-tags: true
          skip-recent: 2
